title: "The slightly delayed 40th birthday 100km running thing"
description: "Fundraising | Raising Awareness <br/><br/> Getting Knackered <br/><br/> and now in 2021"
show_downloads: false

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%a - %b %-d - %Y"

theme: # leave it empty

# Dependencies
# markdown: GFM
# markdown: kramdown

# social
author: bobertsBirthday
# image: /thumbnail-jumbo.png
image: /content/header.png
twitter:
  username: bobertsBirthday
instagram:
  username: bobertsBirthday

plugins:
  - jekyll-target-blank
  - jekyll-gist
  - jemoji

target-blank:
    rel: nofollow

header_page_refs: ['home', 'links', 'cruse', 'samaritans', 'events']
