title: "The 60km, 40th birthday running crazy thing"
description: "Fundraising | Raising Awareness | Getting Knackered"
show_downloads: false

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# Or try
# markdown: GFM
markdown: kramdown

# social
author: BobertsBirthday
image: /thumbnail-jumbo.png
twitter:
  username: BobertsBirthday
instagram:
  username: BobertsBirthday

plugins:
  - jekyll-target-blank
  - jekyll-gist

target-blank:
    rel: nofollow

header_page_refs: ['home', 'links', 'cruse', 'samaritans', 'events']
